# Generated by Django 3.2 on 2021-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionsApp', '0003_stripecustomer_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
