# Generated by Django 3.2 on 2021-04-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionsApp', '0004_alter_stripecustomer_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_amount',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
