# Generated by Django 3.2 on 2021-04-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionsApp', '0005_stripecustomer_stripe_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='stripe_amount',
        ),
    ]
